repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        files: ^middleware/
      - id: check-json
        files: ^middleware/
      - id: check-toml
        files: ^middleware/
      - id: check-yaml
        files: ^middleware/
      - id: check-docstring-first
        files: ^middleware/
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.7
    hooks:
      - id: ruff
        args: [--fix]
        files: ^middleware/
      - id: ruff-format
        files: ^middleware/
  - repo: https://github.com/PyCQA/bandit.git
    rev: 1.7.9
    hooks:
    -   id: bandit
        name: bandit
        description: 'Bandit is a tool for finding common security issues in Python code'
        entry: bandit
        language: python
        language_version: python3
        types: [python]
        require_serial: true
        args: ["--skip", "B101", "--severity-level", "medium"]
        files: ^middleware/
  -   repo: https://github.com/pre-commit/mirrors-mypy
      rev: 'v1.11.1'
      hooks:
      -   id: mypy
          args: [--ignore-missing-imports]
          additional_dependencies: ['types-requests','types-PyYAML']
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
        files: ^middleware/